// Generates a single self-contained export of the whole source tree:
//   docs/FULL_CODE.md
//
// Every file appears in a chapter named after its top-level folder, in
// order, with a code fence you can copy straight back into a file.
//
// Usage: npm run export:code

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "docs", "FULL_CODE.md");

const SKIP_DIRS = new Set(["node_modules", ".git", "docs"]);
const SKIP_FILES = new Set([".env", "package-lock.json"]);

function collect(dir) {
  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name));
  let files = [];
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      files = files.concat(collect(path.join(dir, entry.name)));
    } else {
      const abs = path.join(dir, entry.name);
      if (SKIP_FILES.has(entry.name)) continue;
      if (entry.name.endsWith(".db") || entry.name.endsWith(".db-journal")) continue;
      files.push(abs);
    }
  }
  return files;
}

function langFor(file) {
  const ext = path.extname(file);
  const map = {
    ".js": "js",
    ".prisma": "prisma",
    ".json": "json",
    ".md": "markdown",
    ".env": "bash",
    ".sh": "bash",
    ".sql": "sql",
    ".txt": "text",
  };
  return map[ext] || "text";
}

function tocEntry(files, rootPath) {
  const chapters = new Map();
  for (const f of files) {
    const rel = path.relative(rootPath, f);
    const parts = rel.split(path.sep);
    const key = parts.length > 1 && rootPath !== path.dirname(f) ? parts[0] : "(root)";
    if (!chapters.has(key)) chapters.set(key, []);
    chapters.get(key).push(rel);
  }
  return chapters;
}

function main() {
  const files = collect(ROOT).sort();
  const chapters = tocEntry(files, ROOT);

  const info = [];
  for (const [chapter, rels] of chapters) {
    info.push(`- 📁 **${chapter}** — ${rels.length} file(s)`);
  }

  const lines = [
    "# 📦 Full Code Export",
    "",
    "Single-file export of the entire project, split into **chapters** — one per",
    "top-level folder. Each file is fenced so you can copy it straight back",
    "into its path. Generated by `npm run export:code`.",
    "",
    "## Table of contents",
    "",
    ...info,
    "",
  ];

  let total = 0;
  for (const [chapter, rels] of chapters) {
    lines.push(`## 📁 ${chapter}`);
    lines.push("");
    for (const rel of rels) {
      const abs = path.join(ROOT, rel);
      const src = fs.readFileSync(abs, "utf8");
      const count = src.split("\n").length;
      const noNewline = !src.endsWith("\n");
      total += count;
      lines.push(`### \`${rel}\` — ${count} lines${noNewline ? " (no trailing newline)" : ""}`, "");
      const fence = "```" + langFor(abs);
      lines.push(fence);
      lines.push(src.endsWith("\n") ? src.slice(0, -1) : src);
      lines.push(fence, "");
    }
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, lines.join("\n"));
  console.log(`✅ Wrote ${OUT}`);
  console.log(`   ${files.length} files, ${total} lines, ${chapters.size} chapters`);
}

main();